fetchـandـarchiveـpriceـtask:
  description: >
    Fetch the current Bitcoin price from the Coingecko API using {COINGECKO_API_URL}. 
  expected_output: >
    A record in the archive at {PRICES_ARCHIVE_PATH} containing the latest Bitcoin price.
  agent: price_monitor

scrape_crypto_news_task:
  description: >
    Scrape the latest crypto news headlines and summaries from predefined websites {NEWS_SOURCES} using the ScrapeWebsiteTool. 
    Ensure the data is relevant to the current year, {CURRENT_YEAR}.
  expected_output: >
    A list of relevent news, with title, body, and market sentiment saved at {NEWS_ARCHIVE_PATH}.
  agent: news_monitor

analyze_and_recommend_task:
  description: >
    Analyze the Bitcoin price history from {PRICES_ARCHIVE_PATH} and the current crypto news sentiment and the news stored in {NEWS_ARCHIVE_PATH}. 
    Generate a trading recommendation (buy, sell, or hold) based on the analysis.
  expected_output: >
    A concise trading recommendation (buy, sell, or hold) based on the latest data and news sentiment.
  agent: decision
